version: '3'

services:
  database:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  nodeapp:
    build: ./backend
    ports: 
      - 3001:3001
    restart: always
    depends_on:
      - database
  apache:
    build: ./frontend
    ports:
      - 80:80
